apiVersion: v1
kind: ConfigMap
metadata:
  name: backendconfig
  namespace: expense
data:
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels: # replicaset labels
    app: backend
    tier: api
    project: expense
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels: # selector labels
      app: backend
      tier: api
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: api
        project: expense
    spec:
      containers:
      - name: backend
        image: joindevops/backend:v1
        envFrom:
        - configMapRef:
            name: backendconfig
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
    tier: api
    project: expense
  ports:
  - name: backend-svcport
    protocol: TCP
    port: 8080 #service port
    targetPort: 8080 # container port



